[package]
name = "ampseer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "^0.3"
noodles = { version = "0.13.0", features = ["bam", "fastq"] }